stages:
  - build + deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: boiledsteak/infinity-cleaner-app

services:
  - docker:dind

image: docker:24

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build + deploy:
  stage: build + deploy
  script:
    # Build the frontend first
    - npm update --prefix frontend
    - npm install --prefix frontend
    - npm run build --prefix frontend  # This will generate the 'dist' folder
    # Now build the Docker image with the pre-built frontend
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
