stages:
  - build + deploy


variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: boiledsteak/infinity-cleaner-app

# Use DinD service to run Docker inside the job
services:
  - docker:dind

# Use Docker CLI image (with Docker client installed)
image: docker:24

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build + deploy:
  stage: build + deploy
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest


