services:
  infinity-cleaner-app:
    image: boiledsteak/infinity-cleaner-app:latest
    ports:
      - "4433:8080"  # Expose port 4433 externally and map it to internal port 8080
    networks:
      - app-network
    environment:
      - NODE_ENV=production  # Add any environment variables if needed

networks:
  app-network:
    driver: bridge
