services:
  app:
    build: .
    ports:
      - "4433:8080"  # Exposes container's port 8080 to the host's port 4433
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
