services:
  infinity-cleaner-app:
    image: boiledsteak/infinity-cleaner-app:latest
    ports:
      - "4433:8080"  # Expose port 4433 externally and map it to internal port 8080
    networks:
      - app-network
    environment:
      - NODE_ENV=production  # Add any environment variables if needed
      - DATABASE_URL=postgresql://neondb_owner:npg_zTLSlIk7sJf3@ep-winter-cherry-a1gsnkd8-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

networks:
  app-network:
    driver: bridge
